Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
Traceback (most recent call last):
  File "/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_domain_model.py", line 124, in <module>
    y_train_tensor = np.loadtxt('/rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/'+fname , delimiter=',')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/ak1920/home/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /rds/general/user/ak1920/home/fyp/fyp/pytorch_models/time_series/sub-001-PLCB-ROI0.txt not found.
